import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("sentence_transformers").setLevel(logging.WARNING)
import os
import shutil
from uuid import UUID, uuid4

from dotenv import load_dotenv

from fastapi import (
    FastAPI,
    Depends,
    HTTPException,
    UploadFile,
    File,
    BackgroundTasks,
)

from contextlib import asynccontextmanager

from fastapi.security import OAuth2PasswordRequestForm

from sqlalchemy.orm import Session

from pydantic import BaseModel, EmailStr

from .database import (
    init_db,
    get_db,
)

from .models import (
    User,
    Document,
    Chunk,
    Conversation,
    Message,
    Quiz,
    QuizQuestion,
    QuizAttempt,
)

from .auth import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    decode_refresh_token,
    get_current_user,
)

#port number problem
from fastapi.middleware.cors import CORSMiddleware


# =========================================================
# AI / RAG
# =========================================================

from ai.service import (
    process_document_background,
    generate_quiz,
)

from ai.rag_service import answer_question


# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================

load_dotenv()


# =========================================================
# FASTAPI APPLICATION
# =========================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    yield


app = FastAPI(
    title="StudyMate API",
    description="AI Study Assistant for University Students",
    version="1.0.0",
    lifespan=lifespan,
)

##port number problem
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =========================================================
# CHAT SETTINGS
# =========================================================

# Number of previous messages that will be sent to Claude
# as conversation history.
CHAT_HISTORY_LIMIT = 200


# =========================================================
# PYDANTIC SCHEMAS
# =========================================================


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str
    full_name: str


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str


class RefreshRequest(BaseModel):
    refresh_token: str


class DocumentResponse(BaseModel):
    id: UUID
    title: str
    filename: str
    status: str

    class Config:
        from_attributes = True


class DocumentUpdateRequest(BaseModel):
    title: str

class ChatRequest(BaseModel):
    document_id: UUID
    message: str
    conversation_id: UUID | None = None


class ChatResponse(BaseModel):
    conversation_id: UUID
    answer: str
    sources: list


# =========================================================
# QUIZ SCHEMAS
# =========================================================


class QuizCreateRequest(BaseModel):
    document_id: UUID
    title: str

    # Number of questions generated by AI
    num_questions: int = 10

    # Question type is kept for API compatibility.
    # The AI quiz service currently generates a mixture
    # of multiple-choice, true/false, and short-answer
    # questions.
    question_type: str = "multiple_choice"


class QuizAttemptRequest(BaseModel):
    """
    Example:

    {
        "answers": {
            "question_uuid_1": "A",
            "question_uuid_2": "B",
            "question_uuid_3": "C"
        }
    }
    """

    answers: dict


class QuizQuestionResponse(BaseModel):
    id: UUID
    question_text: str
    question_type: str
    options: dict | list | None
    source_page: int | None

    class Config:
        from_attributes = True


# =========================================================
# ROOT
# =========================================================

@app.get("/")
def home():
    return {
        "message": "Welcome to StudyMate API"
    }


# =========================================================
# AUTHENTICATION - REGISTER
# =========================================================

@app.post("/auth/register")
def register(
    user_data: RegisterRequest,
    db: Session = Depends(get_db),
):
    """
    Register a new user.
    """

    existing_user = (
        db.query(User)
        .filter(
            User.email == user_data.email
        )
        .first()
    )

    if existing_user:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    password_hash = hash_password(
        user_data.password
    )

    user = User(
        email=user_data.email,
        password_hash=password_hash,
        full_name=user_data.full_name,
    )

    db.add(user)
    db.commit()
    db.refresh(user)

    return {
        "message": "User registered successfully",
        "user_id": str(user.id),
    }


# =========================================================
# AUTHENTICATION - LOGIN
# =========================================================

@app.post(
    "/auth/login",
    response_model=TokenResponse,
)
def login(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db),
):
    """
    Login using email and password.

    Swagger OAuth2 uses:

        username = email
        password = password
    """

    user = (
        db.query(User)
        .filter(
            User.email == form_data.username
        )
        .first()
    )

    if not user:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    if not verify_password(
        form_data.password,
        user.password_hash,
    ):
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    access_token = create_access_token(
        data={
            "sub": str(user.id)
        }
    )

    refresh_token = create_refresh_token(
        data={
            "sub": str(user.id)
        }
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
    }

# =========================================================
# AUTHENTICATION - REFRESH TOKEN
# =========================================================

@app.post(
    "/auth/refresh",
    response_model=TokenResponse,
)
def refresh_access_token(
    request_data: RefreshRequest,
    db: Session = Depends(get_db),
):
    """
    Exchange a valid refresh token for a new access token
    (and a new refresh token, rotated for extra safety).
    """

    user_id = decode_refresh_token(
        request_data.refresh_token
    )

    user = (
        db.query(User)
        .filter(User.id == user_id)
        .first()
    )

    if not user:
        raise HTTPException(
            status_code=401,
            detail="User not found",
        )

    new_access_token = create_access_token(
        data={"sub": str(user.id)}
    )

    new_refresh_token = create_refresh_token(
        data={"sub": str(user.id)}
    )

    return {
        "access_token": new_access_token,
        "refresh_token": new_refresh_token,
        "token_type": "bearer",
    }


# =========================================================
# DOCUMENTS - UPLOAD
# =========================================================

@app.post(
    "/documents",
    response_model=DocumentResponse,
)
async def upload_document(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Upload a PDF document.

    The document is first saved to disk and the database.
    RAG processing is then started as a background task.

    The uploaded file is copied in blocks instead of being
    loaded completely into memory.
    """

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is required",
        )

    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are supported",
        )

    os.makedirs(
        "uploads",
        exist_ok=True,
    )

    original_filename = file.filename

    safe_filename = (
        f"{uuid4()}_{original_filename}"
    )

    file_path = os.path.join(
        "uploads",
        safe_filename,
    )

    # -----------------------------------------------------
    # Save uploaded file in blocks
    # -----------------------------------------------------
    #
    # IMPORTANT:
    #
    # Do NOT use:
    #
    #     contents = await file.read()
    #
    # because that loads the entire PDF into memory.
    #
    # Instead, copy the file in chunks.
    # -----------------------------------------------------

    with open(
        file_path,
        "wb",
    ) as buffer:
        shutil.copyfileobj(
            file.file,
            buffer,
            length=1024 * 1024,
        )

    document = Document(
        user_id=current_user.id,
        title=original_filename,
        filename=original_filename,
        file_path=file_path,
        status="pending",
    )

    db.add(document)
    db.commit()
    db.refresh(document)

    background_tasks.add_task(
        process_document_background,
        document.id,
    )

    return document


# =========================================================
# GET ALL DOCUMENTS
# =========================================================

@app.get(
    "/documents",
    response_model=list[DocumentResponse],
)
def get_documents(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all documents belonging to the current user.
    """

    documents = (
        db.query(Document)
        .filter(
            Document.user_id == current_user.id
        )
        .all()
    )

    return documents


# =========================================================
# GET ONE DOCUMENT
# =========================================================

@app.get(
    "/documents/{document_id}",
    response_model=DocumentResponse,
)
def get_document(
    document_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a specific document.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    return document

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    return document


# =========================================================
# UPDATE DOCUMENT TITLE
# =========================================================

@app.patch(
    "/documents/{document_id}",
    response_model=DocumentResponse,
)
def update_document(
    document_id: UUID,
    update_data: DocumentUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Update a document's display title.

    Only the title can be changed here. The underlying
    file, its path, and its processing status are never
    touched by this endpoint.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    new_title = update_data.title.strip()

    if not new_title:
        raise HTTPException(
            status_code=400,
            detail="Title cannot be empty",
        )

    document.title = new_title

    db.commit()
    db.refresh(document)

    return document

# =========================================================
# DELETE DOCUMENT
# =========================================================

@app.delete(
    "/documents/{document_id}"
)
def delete_document(
    document_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a document and its physical file.

    Related chunks, conversations and quizzes
    are deleted through database cascade relationships.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    if (
        document.file_path
        and os.path.exists(document.file_path)
    ):
        os.remove(document.file_path)

    db.delete(document)
    db.commit()

    return {
        "message": "Document deleted successfully"
    }


# =========================================================
# CHAT
# =========================================================

@app.post(
    "/chat",
    response_model=ChatResponse,
)
def chat(
    chat_data: ChatRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Chat with a document using the RAG pipeline.

    The endpoint also loads the last few messages from
    the current conversation and passes them to the AI
    so that Claude can understand follow-up questions.
    """

    # -----------------------------------------------------
    # Validate message
    # -----------------------------------------------------

    if not chat_data.message.strip():
        raise HTTPException(
            status_code=400,
            detail="Message cannot be empty",
        )

    # -----------------------------------------------------
    # Validate document ownership
    # -----------------------------------------------------

    document = (
        db.query(Document)
        .filter(
            Document.id == chat_data.document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # -----------------------------------------------------
    # Document must be ready
    # -----------------------------------------------------

    if document.status != "ready":
        raise HTTPException(
            status_code=400,
            detail=(
                f"Document is not ready. "
                f"Current status: {document.status}"
            ),
        )

    # -----------------------------------------------------
    # Find existing conversation
    # -----------------------------------------------------

    conversation = None

    if chat_data.conversation_id:

        conversation = (
            db.query(Conversation)
            .filter(
                Conversation.id
                == chat_data.conversation_id,
                Conversation.user_id
                == current_user.id,
                Conversation.document_id
                == document.id,
            )
            .first()
        )

        if not conversation:
            raise HTTPException(
                status_code=404,
                detail="Conversation not found",
            )

    # -----------------------------------------------------
    # Create a new conversation if needed
    # -----------------------------------------------------

    if conversation is None:

        conversation = Conversation(
            user_id=current_user.id,
            document_id=document.id,
            title=chat_data.message[:255],
        )

        db.add(conversation)
        db.commit()
        db.refresh(conversation)

    # -----------------------------------------------------
    # LOAD PREVIOUS CONVERSATION MESSAGES
    # -----------------------------------------------------
    #
    # IMPORTANT:
    #
    # We load the previous messages BEFORE saving the
    # current user question.
    #
    # This means conversation_history contains only
    # messages that happened before the current question.
    #
    # Example:
    #
    # User: What is supply and demand?
    # Assistant: ...
    #
    # New question:
    # Explain that more simply.
    #
    # The history sent to Claude will contain the first
    # question and answer, while the new question is
    # sent separately.
    # -----------------------------------------------------

    previous_messages = (
        db.query(Message)
        .filter(
            Message.conversation_id
            == conversation.id
        )
        .order_by(
            Message.created_at.desc()
        )
        .limit(
            CHAT_HISTORY_LIMIT
        )
        .all()
    )

    # -----------------------------------------------------
    # Restore chronological order
    # -----------------------------------------------------
    #
    # The database query above returns the newest
    # messages first.
    #
    # Claude should receive them from oldest to newest.
    # -----------------------------------------------------

    previous_messages.reverse()

    # -----------------------------------------------------
    # Convert database messages into Claude format
    # -----------------------------------------------------

    conversation_history = [
        {
            "role": message.role,
            "content": message.content,
        }
        for message in previous_messages
    ]

    # -----------------------------------------------------
    # Save current user message
    # -----------------------------------------------------

    user_message = Message(
        conversation_id=conversation.id,
        role="user",
        content=chat_data.message,
        sources=[],
    )

    db.add(user_message)
    db.commit()

    # -----------------------------------------------------
    # Run RAG + conversation memory
    # -----------------------------------------------------

    try:

        rag_result = answer_question(
            db=db,
            document_id=document.id,
            question=chat_data.message,
            conversation_history=conversation_history,
        )

    except ValueError as error:

        raise HTTPException(
            status_code=400,
            detail=str(error),
        )

    except RuntimeError as error:

        raise HTTPException(
            status_code=503,
            detail=str(error),
        )

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=(
                "An error occurred while processing "
                "the AI request."
            ),
        ) from error

    # -----------------------------------------------------
    # Save assistant response
    # -----------------------------------------------------

    assistant_message = Message(
        conversation_id=conversation.id,
        role="assistant",
        content=rag_result["answer"],
        sources=rag_result["sources"],
    )

    db.add(assistant_message)
    db.commit()

    # -----------------------------------------------------
    # Return response
    # -----------------------------------------------------

    return {
        "conversation_id": conversation.id,
        "answer": rag_result["answer"],
        "sources": rag_result["sources"],
    }


# =========================================================
# CONVERSATIONS
# =========================================================

@app.get("/conversations")
def get_conversations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all conversations belonging to the current user.
    """

    conversations = (
        db.query(Conversation)
        .filter(
            Conversation.user_id == current_user.id
        )
        .order_by(
            Conversation.created_at.desc()
        )
        .all()
    )

    return conversations


# =========================================================
# GET ONE CONVERSATION
# =========================================================

@app.get(
    "/conversations/{conversation_id}"
)
def get_conversation(
    conversation_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a conversation and its messages.
    """

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == conversation_id,
            Conversation.user_id == current_user.id,
        )
        .first()
    )

    if not conversation:
        raise HTTPException(
            status_code=404,
            detail="Conversation not found",
        )

    messages = (
        db.query(Message)
        .filter(
            Message.conversation_id
            == conversation.id
        )
        .order_by(
            Message.created_at
        )
        .all()
    )

    return {
        "conversation": conversation,
        "messages": messages,
    }


# =========================================================
# CREATE QUIZ
# =========================================================

@app.post("/quizzes")
def create_quiz(
    quiz_data: QuizCreateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Create an AI-generated quiz.

    The API endpoint is responsible for:

        1. Validating the document.
        2. Creating the Quiz record.
        3. Delegating AI quiz generation to ai.service.

    The actual AI generation logic is implemented
    in ai/service.py.
    """

    # -----------------------------------------------------
    # Validate document ownership
    # -----------------------------------------------------

    document = (
        db.query(Document)
        .filter(
            Document.id == quiz_data.document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:

        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # -----------------------------------------------------
    # Document must be ready
    # -----------------------------------------------------

    if document.status != "ready":

        raise HTTPException(
            status_code=400,
            detail=(
                f"Document is not ready. "
                f"Current status: {document.status}"
            ),
        )

    # -----------------------------------------------------
    # Validate number of questions
    # -----------------------------------------------------

    if quiz_data.num_questions < 1:

        raise HTTPException(
            status_code=400,
            detail="num_questions must be at least 1",
        )

    if quiz_data.num_questions > 50:

        raise HTTPException(
            status_code=400,
            detail="num_questions cannot exceed 50",
        )

    # -----------------------------------------------------
    # Create Quiz record
    # -----------------------------------------------------

    quiz = Quiz(
        user_id=current_user.id,
        document_id=document.id,
        title=quiz_data.title,
    )

    db.add(quiz)
    db.flush()

    # -----------------------------------------------------
    # Generate questions through AI service
    # -----------------------------------------------------

    try:

        generated_questions = generate_quiz(
            db=db,
            quiz=quiz,
            question_count=quiz_data.num_questions,
        )

    except ValueError as error:

        db.rollback()

        raise HTTPException(
            status_code=400,
            detail=str(error),
        )

    except RuntimeError as error:

        db.rollback()

        raise HTTPException(
            status_code=503,
            detail=str(error),
        )

    except Exception as error:

        db.rollback()

        raise HTTPException(
            status_code=500,
            detail=(
                "An error occurred while generating "
                "the quiz."
            ),
        ) from error

    # -----------------------------------------------------
    # Return result
    # -----------------------------------------------------

    return {
        "message": "Quiz created successfully",
        "quiz_id": str(quiz.id),
        "questions_count": len(
            generated_questions
        ),
    }


# =========================================================
# GET QUIZ
# =========================================================

@app.get("/quizzes/{quiz_id}")
def get_quiz(
    quiz_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a quiz and its questions.

    IMPORTANT:

    correct_answer and explanation are NOT returned
    because they must remain hidden from the student
    until the quiz is submitted.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .order_by(
            QuizQuestion.question_index
        )
        .all()
    )

    return {
        "quiz": {
            "id": quiz.id,
            "title": quiz.title,
            "document_id": quiz.document_id,
            "created_at": quiz.created_at,
        },

        "questions": [
            QuizQuestionResponse.model_validate(
                question
            )
            for question in questions
        ],
    }


# =========================================================
# SUBMIT QUIZ ATTEMPT
# =========================================================

@app.post(
    "/quizzes/{quiz_id}/attempts"
)
def submit_quiz_attempt(
    quiz_id: UUID,
    attempt_data: QuizAttemptRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Submit answers and calculate the final score.

    Student answers are compared directly with
    the correct answers stored in QuizQuestion.
    """

    # -----------------------------------------------------
    # Find quiz
    # -----------------------------------------------------

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    # -----------------------------------------------------
    # Get questions
    # -----------------------------------------------------

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .all()
    )

    if not questions:

        raise HTTPException(
            status_code=400,
            detail="This quiz has no questions.",
        )

    # -----------------------------------------------------
    # Validate answers
    # -----------------------------------------------------

    submitted_answers = (
        attempt_data.answers
    )

    score = 0
    total_questions = len(questions)

    results = []

    # -----------------------------------------------------
    # Compare answers
    # -----------------------------------------------------

    for question in questions:

        question_id = str(
            question.id
        )

        student_answer = submitted_answers.get(
            question_id
        )

        if student_answer is not None:

            student_answer = str(
                student_answer
            ).strip().upper()

        correct_answer = (
            str(
                question.correct_answer
            )
            .strip()
            .upper()
        )

        is_correct = (
            student_answer
            == correct_answer
        )

        if is_correct:
            score += 1

        results.append(
            {
                "question_id": question_id,
                "student_answer": student_answer,
                "correct": is_correct,
            }
        )

    # -----------------------------------------------------
    # Calculate percentage
    # -----------------------------------------------------

    percentage = round(
        (score / total_questions) * 100,
        2,
    )

    # -----------------------------------------------------
    # Save attempt
    # -----------------------------------------------------

    attempt = QuizAttempt(
        quiz_id=quiz.id,
        user_id=current_user.id,
        score=score,
        answers=submitted_answers,
    )

    db.add(attempt)
    db.commit()
    db.refresh(attempt)

    # -----------------------------------------------------
    # Return final result
    # -----------------------------------------------------

    return {
        "message": "Quiz attempt submitted successfully",

        "attempt_id": str(
            attempt.id
        ),

        "score": score,

        "total_questions": total_questions,

        "percentage": percentage,

        "correct_answers": score,

        "wrong_answers": (
            total_questions - score
        ),

        "results": results,
    }