import json
import os
from uuid import UUID, uuid4

from anthropic import (
    Anthropic,
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    RateLimitError,
)

from dotenv import load_dotenv

from fastapi import (
    FastAPI,
    Depends,
    HTTPException,
    UploadFile,
    File,
    BackgroundTasks,
)

from fastapi.security import OAuth2PasswordRequestForm

from sqlalchemy.orm import Session

from pydantic import BaseModel, EmailStr

from .database import (
    init_db,
    get_db,
)

from .models import (
    User,
    Document,
    Chunk,
    Conversation,
    Message,
    Quiz,
    QuizQuestion,
    QuizAttempt,
)

from .auth import (
    hash_password,
    verify_password,
    create_access_token,
    get_current_user,
)

# =========================================================
# AI / RAG
# =========================================================

from ai.service import process_document_background
from ai.rag_service import answer_question


# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================

load_dotenv()


# =========================================================
# FASTAPI APPLICATION
# =========================================================

app = FastAPI(
    title="StudyMate API",
    description="AI Study Assistant for University Students",
    version="1.0.0",
)


# =========================================================
# STARTUP
# =========================================================

@app.on_event("startup")
def startup():
    """
    Initialize database tables when the application starts.
    """

    init_db()


# =========================================================
# PYDANTIC SCHEMAS
# =========================================================


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str
    full_name: str


class TokenResponse(BaseModel):
    access_token: str
    token_type: str


class DocumentResponse(BaseModel):
    id: UUID
    title: str
    filename: str
    status: str

    class Config:
        from_attributes = True


class ChatRequest(BaseModel):
    document_id: UUID
    message: str
    conversation_id: UUID | None = None


class ChatResponse(BaseModel):
    conversation_id: UUID
    answer: str
    sources: list


# =========================================================
# QUIZ SCHEMAS
# =========================================================


class QuizCreateRequest(BaseModel):
    document_id: UUID
    title: str

    # Number of questions generated by AI
    num_questions: int = 10

    # Currently supported:
    # multiple_choice
    question_type: str = "multiple_choice"


class QuizAttemptRequest(BaseModel):
    """
    Example:

    {
        "answers": {
            "question_uuid_1": "A",
            "question_uuid_2": "B",
            "question_uuid_3": "C"
        }
    }
    """

    answers: dict


class QuizQuestionResponse(BaseModel):
    id: UUID
    question_text: str
    question_type: str
    options: dict | list | None
    source_page: int | None

    class Config:
        from_attributes = True


# =========================================================
# ROOT
# =========================================================

@app.get("/")
def home():
    return {
        "message": "Welcome to StudyMate API"
    }


# =========================================================
# AUTHENTICATION - REGISTER
# =========================================================

@app.post("/auth/register")
def register(
    user_data: RegisterRequest,
    db: Session = Depends(get_db),
):
    """
    Register a new user.
    """

    existing_user = (
        db.query(User)
        .filter(
            User.email == user_data.email
        )
        .first()
    )

    if existing_user:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    password_hash = hash_password(
        user_data.password
    )

    user = User(
        email=user_data.email,
        password_hash=password_hash,
        full_name=user_data.full_name,
    )

    db.add(user)
    db.commit()
    db.refresh(user)

    return {
        "message": "User registered successfully",
        "user_id": str(user.id),
    }


# =========================================================
# AUTHENTICATION - LOGIN
# =========================================================

@app.post(
    "/auth/login",
    response_model=TokenResponse,
)
def login(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db),
):
    """
    Login using email and password.

    Swagger OAuth2 uses:

        username = email
        password = password
    """

    user = (
        db.query(User)
        .filter(
            User.email == form_data.username
        )
        .first()
    )

    if not user:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    if not verify_password(
        form_data.password,
        user.password_hash,
    ):
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    access_token = create_access_token(
        data={
            "sub": str(user.id)
        }
    )

    return {
        "access_token": access_token,
        "token_type": "bearer",
    }


# =========================================================
# DOCUMENTS - UPLOAD
# =========================================================

@app.post(
    "/documents",
    response_model=DocumentResponse,
)
async def upload_document(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Upload a PDF document.

    The document is first saved to disk and the database.
    RAG processing is then started as a background task.
    """

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is required",
        )

    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are supported",
        )

    os.makedirs(
        "uploads",
        exist_ok=True,
    )

    original_filename = file.filename

    safe_filename = (
        f"{uuid4()}_{original_filename}"
    )

    file_path = os.path.join(
        "uploads",
        safe_filename,
    )

    contents = await file.read()

    with open(
        file_path,
        "wb",
    ) as buffer:
        buffer.write(contents)

    document = Document(
        user_id=current_user.id,
        title=original_filename,
        filename=original_filename,
        file_path=file_path,
        status="pending",
    )

    db.add(document)
    db.commit()
    db.refresh(document)

    background_tasks.add_task(
        process_document_background,
        document.id,
    )

    return document


# =========================================================
# GET ALL DOCUMENTS
# =========================================================

@app.get(
    "/documents",
    response_model=list[DocumentResponse],
)
def get_documents(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all documents belonging to the current user.
    """

    documents = (
        db.query(Document)
        .filter(
            Document.user_id == current_user.id
        )
        .all()
    )

    return documents


# =========================================================
# GET ONE DOCUMENT
# =========================================================

@app.get(
    "/documents/{document_id}",
    response_model=DocumentResponse,
)
def get_document(
    document_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a specific document.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    return document


# =========================================================
# DELETE DOCUMENT
# =========================================================

@app.delete(
    "/documents/{document_id}"
)
def delete_document(
    document_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a document and its physical file.

    Related chunks, conversations and quizzes
    are deleted through database cascade relationships.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    if (
        document.file_path
        and os.path.exists(document.file_path)
    ):
        os.remove(document.file_path)

    db.delete(document)
    db.commit()

    return {
        "message": "Document deleted successfully"
    }


# =========================================================
# CHAT
# =========================================================

@app.post(
    "/chat",
    response_model=ChatResponse,
)
def chat(
    chat_data: ChatRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Chat with a document using the RAG pipeline.
    """

    if not chat_data.message.strip():
        raise HTTPException(
            status_code=400,
            detail="Message cannot be empty",
        )

    document = (
        db.query(Document)
        .filter(
            Document.id == chat_data.document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    if document.status != "ready":
        raise HTTPException(
            status_code=400,
            detail=(
                f"Document is not ready. "
                f"Current status: {document.status}"
            ),
        )

    conversation = None

    if chat_data.conversation_id:

        conversation = (
            db.query(Conversation)
            .filter(
                Conversation.id
                == chat_data.conversation_id,
                Conversation.user_id
                == current_user.id,
                Conversation.document_id
                == document.id,
            )
            .first()
        )

        if not conversation:
            raise HTTPException(
                status_code=404,
                detail="Conversation not found",
            )

    if conversation is None:

        conversation = Conversation(
            user_id=current_user.id,
            document_id=document.id,
            title=chat_data.message[:255],
        )

        db.add(conversation)
        db.commit()
        db.refresh(conversation)

    user_message = Message(
        conversation_id=conversation.id,
        role="user",
        content=chat_data.message,
        sources=[],
    )

    db.add(user_message)
    db.commit()

    try:

        rag_result = answer_question(
            db=db,
            document_id=document.id,
            question=chat_data.message,
        )

    except ValueError as error:

        raise HTTPException(
            status_code=400,
            detail=str(error),
        )

    except RuntimeError as error:

        raise HTTPException(
            status_code=503,
            detail=str(error),
        )

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=(
                "An error occurred while processing "
                "the AI request."
            ),
        ) from error

    assistant_message = Message(
        conversation_id=conversation.id,
        role="assistant",
        content=rag_result["answer"],
        sources=rag_result["sources"],
    )

    db.add(assistant_message)
    db.commit()

    return {
        "conversation_id": conversation.id,
        "answer": rag_result["answer"],
        "sources": rag_result["sources"],
    }


# =========================================================
# CONVERSATIONS
# =========================================================

@app.get("/conversations")
def get_conversations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all conversations belonging to the current user.
    """

    conversations = (
        db.query(Conversation)
        .filter(
            Conversation.user_id == current_user.id
        )
        .order_by(
            Conversation.created_at.desc()
        )
        .all()
    )

    return conversations


# =========================================================
# GET ONE CONVERSATION
# =========================================================

@app.get(
    "/conversations/{conversation_id}"
)
def get_conversation(
    conversation_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a conversation and its messages.
    """

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == conversation_id,
            Conversation.user_id == current_user.id,
        )
        .first()
    )

    if not conversation:
        raise HTTPException(
            status_code=404,
            detail="Conversation not found",
        )

    messages = (
        db.query(Message)
        .filter(
            Message.conversation_id
            == conversation.id
        )
        .order_by(
            Message.created_at
        )
        .all()
    )

    return {
        "conversation": conversation,
        "messages": messages,
    }


# =========================================================
# CLAUDE CLIENT FOR QUIZ GENERATION
# =========================================================

def get_claude_client() -> Anthropic:
    """
    Create the Anthropic client using the API key
    from .env.
    """

    api_key = os.getenv(
        "ANTHROPIC_API_KEY"
    )

    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is missing "
            "from the .env file"
        )

    return Anthropic(
        api_key=api_key
    )


# =========================================================
# GENERATE QUIZ QUESTIONS WITH AI
# =========================================================

def generate_quiz_questions(
    chunks: list[Chunk],
    num_questions: int,
    question_type: str,
) -> list[dict]:
    """
    Generate quiz questions using Claude.

    Claude receives only the document chunks.
    Therefore the questions are generated from
    the uploaded document.
    """

    if not chunks:
        raise ValueError(
            "The document has no chunks."
        )

    if num_questions < 1:
        raise ValueError(
            "num_questions must be at least 1"
        )

    if num_questions > 50:
        raise ValueError(
            "num_questions cannot exceed 50"
        )

    if question_type != "multiple_choice":
        raise ValueError(
            "Currently only multiple_choice "
            "questions are supported."
        )

    # -----------------------------------------------------
    # Build document context
    # -----------------------------------------------------

    context_parts = []

    for chunk in chunks:

        context_parts.append(
            f"""
PAGE: {chunk.page_number}

CONTENT:
{chunk.content}
""".strip()
        )

    context = "\n\n----------------\n\n".join(
        context_parts
    )

    # -----------------------------------------------------
    # Get model
    # -----------------------------------------------------

    claude_model = os.getenv(
        "CLAUDE_MODEL"
    )

    if not claude_model:
        raise RuntimeError(
            "CLAUDE_MODEL is missing "
            "from the .env file"
        )

    # -----------------------------------------------------
    # Prompt
    # -----------------------------------------------------

    prompt = f"""
You are the quiz-generation AI for StudyMate.

Create exactly {num_questions}
multiple-choice questions using ONLY the
document content provided below.

Do not use outside knowledge.

Each question must have:

- question_text
- question_type
- options
- correct_answer
- explanation
- source_page

Rules:

1. question_type must be "multiple_choice".
2. options must contain exactly four choices:
   A, B, C, D.
3. correct_answer must be exactly one of:
   A, B, C, D.
4. The correct answer must be supported by the document.
5. source_page must be the page where the information
   used to create the question appears.
6. explanation must explain why the correct answer
   is correct using the document.
7. Do not invent information.
8. Return ONLY valid JSON.
9. Do not use Markdown.
10. Return a JSON array.

Expected format:

[
  {{
    "question_text": "What is ...?",
    "question_type": "multiple_choice",
    "options": {{
      "A": "...",
      "B": "...",
      "C": "...",
      "D": "..."
    }},
    "correct_answer": "A",
    "explanation": "...",
    "source_page": 8
  }}
]

DOCUMENT:

{context}
""".strip()

    # -----------------------------------------------------
    # Call Claude
    # -----------------------------------------------------

    client = get_claude_client()

    try:

        response = client.messages.create(
            model=claude_model,
            max_tokens=6000,
            temperature=0,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
        )

    except RateLimitError as error:

        raise RuntimeError(
            "The AI service rate limit was reached."
        ) from error

    except APITimeoutError as error:

        raise RuntimeError(
            "The AI service took too long to respond."
        ) from error

    except APIConnectionError as error:

        raise RuntimeError(
            "Could not connect to the AI service."
        ) from error

    except APIStatusError as error:

        raise RuntimeError(
            f"The AI service returned an error: {error}"
        ) from error

    # -----------------------------------------------------
    # Extract response text
    # -----------------------------------------------------

    text_parts = [
        block.text
        for block in response.content
        if block.type == "text"
    ]

    response_text = "\n".join(
        text_parts
    ).strip()

    if not response_text:
        raise RuntimeError(
            "Claude returned an empty quiz response."
        )

    # -----------------------------------------------------
    # Parse JSON
    # -----------------------------------------------------

    try:

        questions = json.loads(
            response_text
        )

    except json.JSONDecodeError as error:

        raise RuntimeError(
            "Claude returned invalid JSON "
            "while generating the quiz."
        ) from error

    if not isinstance(
        questions,
        list,
    ):
        raise RuntimeError(
            "Claude quiz response must be a JSON array."
        )

    # -----------------------------------------------------
    # Validate generated questions
    # -----------------------------------------------------

    validated_questions = []

    for question in questions:

        if not isinstance(
            question,
            dict,
        ):
            continue

        required_fields = [
            "question_text",
            "question_type",
            "options",
            "correct_answer",
            "explanation",
            "source_page",
        ]

        if not all(
            field in question
            for field in required_fields
        ):
            continue

        options = question["options"]

        if not isinstance(
            options,
            dict,
        ):
            continue

        required_options = {
            "A",
            "B",
            "C",
            "D",
        }

        if set(options.keys()) != required_options:
            continue

        correct_answer = str(
            question["correct_answer"]
        ).upper()

        if correct_answer not in {
            "A",
            "B",
            "C",
            "D",
        }:
            continue

        validated_questions.append(
            {
                "question_text": str(
                    question["question_text"]
                ).strip(),

                "question_type": "multiple_choice",

                "options": options,

                "correct_answer": correct_answer,

                "explanation": str(
                    question["explanation"]
                ).strip(),

                "source_page": question[
                    "source_page"
                ],
            }
        )

    if len(validated_questions) != num_questions:
        raise RuntimeError(
            f"Claude generated {len(validated_questions)} valid questions, "
            f"but {num_questions} questions were requested."
        )

    return validated_questions



# =========================================================
# CREATE QUIZ
# =========================================================

@app.post("/quizzes")
def create_quiz(
    quiz_data: QuizCreateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Create an AI-generated quiz.

    Flow:

        Document
            ↓
        Chunks
            ↓
        Claude
            ↓
        Questions
            ↓
        QuizQuestion records
    """

    # -----------------------------------------------------
    # Validate document ownership
    # -----------------------------------------------------

    document = (
        db.query(Document)
        .filter(
            Document.id == quiz_data.document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:

        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # -----------------------------------------------------
    # Document must be ready
    # -----------------------------------------------------

    if document.status != "ready":

        raise HTTPException(
            status_code=400,
            detail=(
                f"Document is not ready. "
                f"Current status: {document.status}"
            ),
        )

    # -----------------------------------------------------
    # Get document chunks
    # -----------------------------------------------------

    chunks = (
        db.query(Chunk)
        .filter(
            Chunk.document_id == document.id
        )
        .order_by(
            Chunk.chunk_index
        )
        .all()
    )

    if not chunks:

        raise HTTPException(
            status_code=400,
            detail=(
                "No chunks were found for this document."
            ),
        )

    # -----------------------------------------------------
    # Generate questions using Claude
    # -----------------------------------------------------

    try:

        generated_questions = (
            generate_quiz_questions(
                chunks=chunks,
                num_questions=quiz_data.num_questions,
                question_type=quiz_data.question_type,
            )
        )

    except ValueError as error:

        raise HTTPException(
            status_code=400,
            detail=str(error),
        )

    except RuntimeError as error:

        raise HTTPException(
            status_code=503,
            detail=str(error),
        )

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=(
                "An error occurred while generating "
                "the quiz."
            ),
        ) from error

    # -----------------------------------------------------
    # Create Quiz
    # -----------------------------------------------------

    quiz = Quiz(
        user_id=current_user.id,
        document_id=document.id,
        title=quiz_data.title,
    )

    db.add(quiz)
    db.flush()

    # -----------------------------------------------------
    # Create QuizQuestion records
    # -----------------------------------------------------

    for generated_question in generated_questions:

        question = QuizQuestion(
            quiz_id=quiz.id,
            question_text=(
                generated_question[
                    "question_text"
                ]
            ),
            question_type=(
                generated_question[
                    "question_type"
                ]
            ),
            options=(
                generated_question[
                    "options"
                ]
            ),
            correct_answer=(
                generated_question[
                    "correct_answer"
                ]
            ),
            explanation=(
                generated_question[
                    "explanation"
                ]
            ),
            source_page=(
                generated_question[
                    "source_page"
                ]
            ),
        )

        db.add(question)

    # -----------------------------------------------------
    # Commit everything
    # -----------------------------------------------------

    db.commit()
    db.refresh(quiz)

    return {
        "message": "Quiz created successfully",
        "quiz_id": str(quiz.id),
        "questions_count": len(
            generated_questions
        ),
    }


# =========================================================
# GET QUIZ
# =========================================================

@app.get("/quizzes/{quiz_id}")
def get_quiz(
    quiz_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a quiz and its questions.

    IMPORTANT:

    correct_answer and explanation are NOT returned
    because they must remain hidden from the student
    until the quiz is submitted.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .order_by(
            QuizQuestion.id
        )
        .all()
    )

    return {
        "quiz": {
            "id": quiz.id,
            "title": quiz.title,
            "document_id": quiz.document_id,
            "created_at": quiz.created_at,
        },

        "questions": [
            QuizQuestionResponse.model_validate(
                question
            )
            for question in questions
        ],
    }


# =========================================================
# SUBMIT QUIZ ATTEMPT
# =========================================================

@app.post(
    "/quizzes/{quiz_id}/attempts"
)
def submit_quiz_attempt(
    quiz_id: UUID,
    attempt_data: QuizAttemptRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Submit answers and calculate the final score.

    Student answers are compared directly with
    the correct answers stored in QuizQuestion.
    """

    # -----------------------------------------------------
    # Find quiz
    # -----------------------------------------------------

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    # -----------------------------------------------------
    # Get questions
    # -----------------------------------------------------

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .all()
    )

    if not questions:

        raise HTTPException(
            status_code=400,
            detail="This quiz has no questions.",
        )

    # -----------------------------------------------------
    # Validate answers
    # -----------------------------------------------------

    submitted_answers = (
        attempt_data.answers
    )

    score = 0
    total_questions = len(questions)

    results = []

    # -----------------------------------------------------
    # Compare answers
    # -----------------------------------------------------

    for question in questions:

        question_id = str(
            question.id
        )

        student_answer = submitted_answers.get(
            question_id
        )

        if student_answer is not None:

            student_answer = str(
                student_answer
            ).strip().upper()

        correct_answer = (
            str(
                question.correct_answer
            )
            .strip()
            .upper()
        )

        is_correct = (
            student_answer
            == correct_answer
        )

        if is_correct:
            score += 1

        results.append(
            {
                "question_id": question_id,
                "student_answer": student_answer,
                "correct": is_correct,
            }
        )

    # -----------------------------------------------------
    # Calculate percentage
    # -----------------------------------------------------

    percentage = round(
        (score / total_questions) * 100,
        2,
    )

    # -----------------------------------------------------
    # Save attempt
    # -----------------------------------------------------

    attempt = QuizAttempt(
        quiz_id=quiz.id,
        user_id=current_user.id,
        score=score,
        answers=submitted_answers,
    )

    db.add(attempt)
    db.commit()
    db.refresh(attempt)

    # -----------------------------------------------------
    # Return final result
    # -----------------------------------------------------

    return {
        "message": "Quiz attempt submitted successfully",

        "attempt_id": str(
            attempt.id
        ),

        "score": score,

        "total_questions": total_questions,

        "percentage": percentage,

        "correct_answers": score,

        "wrong_answers": (
            total_questions - score
        ),

        "results": results,
    }