import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("sentence_transformers").setLevel(logging.WARNING)
logger = logging.getLogger(__name__)
import os
import shutil
from uuid import UUID, uuid4

from dotenv import load_dotenv

from fastapi import (
    FastAPI,
    Depends,
    HTTPException,
    UploadFile,
    File,
    BackgroundTasks,
)

from contextlib import asynccontextmanager

from fastapi.security import OAuth2PasswordRequestForm

from sqlalchemy.orm import Session

from pydantic import BaseModel, EmailStr, Field

from concurrent.futures import ThreadPoolExecutor

from .database import (
    init_db,
    get_db,
)

from .models import (
    User,
    Document,
    Chunk,
    Conversation,
    Message,
    Quiz,
    QuizQuestion,
    QuizAttempt,
)

from .auth import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    decode_refresh_token,
    get_current_user,
)

#port number problem
from fastapi.middleware.cors import CORSMiddleware


# =========================================================
# AI / RAG
# =========================================================

from ai.service import (
    process_document_background,
    generate_quiz,
    grade_short_answer,
    QUESTION_TYPES,
)

from ai.rag_service import answer_question


# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================

load_dotenv()


# =========================================================
# FASTAPI APPLICATION
# =========================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    yield


app = FastAPI(
    title="StudyMate API",
    description="AI Study Assistant for University Students",
    version="1.0.0",
    lifespan=lifespan,
)

##port number problem
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =========================================================
# CHAT SETTINGS
# =========================================================

# Number of previous messages that will be sent to Claude
# as conversation history.
CHAT_HISTORY_LIMIT = 50


# =========================================================
# PYDANTIC SCHEMAS
# =========================================================


# The one place a password length is decided. Registration
# and the password change below both read it, so the two can
# never drift apart and accept different passwords.
#
# 8 is the number the registration form has always shown the
# student ("Use at least 8 characters."); until now nothing
# enforced it, so the form was making a promise the API did
# not keep.
MIN_PASSWORD_LENGTH = 8


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=MIN_PASSWORD_LENGTH)
    full_name: str


class UserResponse(BaseModel):
    """
    Who the session belongs to.

    Returned by GET and PATCH /auth/me alike, so the browser
    reads one shape whichever of the two it called.
    """

    id: UUID
    email: EmailStr
    full_name: str


class ProfileUpdateRequest(BaseModel):
    """
    The one part of the account the student can edit.

    The email is not here: it is the login identifier and is
    unique across the table, so changing it is a different job
    with different failure modes.
    """

    full_name: str


class ChangePasswordRequest(BaseModel):
    """
    The current password is required as well as the new one.

    An access token alone is not enough to change a password:
    a borrowed token would otherwise be enough to take the
    account, and knowing the current password is the only
    thing that separates the owner from whoever is holding the
    token.
    """

    current_password: str
    new_password: str = Field(min_length=MIN_PASSWORD_LENGTH)


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str


class RefreshRequest(BaseModel):
    refresh_token: str


class DocumentResponse(BaseModel):
    id: UUID
    title: str
    filename: str
    status: str

    class Config:
        from_attributes = True


class DocumentUpdateRequest(BaseModel):
    title: str

class ChatRequest(BaseModel):
    document_id: UUID
    message: str
    conversation_id: UUID | None = None


class ChatResponse(BaseModel):
    conversation_id: UUID
    answer: str
    sources: list


# =========================================================
# QUIZ SCHEMAS
# =========================================================


class QuizCreateRequest(BaseModel):
    document_id: UUID
    title: str

    # Number of questions generated by AI
    num_questions: int = 10

    # Which kinds of question to generate. Omitted or empty
    # means all three, which is what this endpoint did before
    # the choice existed.
    #
    # This replaces the old singular `question_type`, which was
    # accepted and then ignored - the quiz was always a mixture
    # whatever was sent.
    question_types: list[str] | None = None

    # Free text from the student: what the quiz should
    # concentrate on. It steers generation and is then
    # discarded - it is not stored with the quiz.
    description: str | None = None

    # Restrict generation to part of the document. These are the
    # PDF's own page numbers, counted from the first physical
    # page of the file, which is often not the number printed on
    # the page. Both or neither: half a range is a mistake, not
    # an open end, and is rejected rather than guessed at.
    start_page: int | None = None
    end_page: int | None = None


class QuizUpdateRequest(BaseModel):
    """
    The editable parts of a saved quiz: its title and whether it
    is pinned.

    The questions, the document behind them and every recorded
    attempt stay exactly as they are.

    Both fields are optional because a rename and a pin arrive
    separately - the pin control does not know or resend the
    title. Sending neither is refused rather than treated as a
    no-op; see update_quiz.
    """

    title: str | None = None
    is_pinned: bool | None = None


class ConversationUpdateRequest(BaseModel):
    """
    The editable parts of a conversation, in the same shape as
    QuizUpdateRequest so the two endpoints behave alike.

    A conversation's title starts as the first question the
    student asked, which is why it is worth being able to change.
    """

    title: str | None = None
    is_pinned: bool | None = None


# The widest duration an attempt is allowed to report, in
# seconds: 24 hours. Not a judgement about how long a quiz
# should take - it is the point past which the number is
# obviously not a sitting, but a tab left open overnight or a
# clock that was changed underneath the page.
MAX_ATTEMPT_DURATION_SECONDS = 86400


class QuizAttemptRequest(BaseModel):
    """
    Example:

    {
        "answers": {
            "question_uuid_1": "A",
            "question_uuid_2": "B",
            "question_uuid_3": "C"
        },
        "duration_seconds": 245
    }
    """

    answers: dict

    # Optional, and it stays optional: the browser measures
    # this, so a client that does not send it - an older one,
    # or a page whose stored start time was cleared - must
    # still be able to submit a perfectly good attempt.
    duration_seconds: int | None = None


class QuizQuestionResponse(BaseModel):
    id: UUID
    question_text: str
    question_type: str
    options: dict | list | None
    source_page: int | None

    class Config:
        from_attributes = True


# =========================================================
# ROOT
# =========================================================

@app.get("/")
def home():
    return {
        "message": "Welcome to StudyMate API"
    }


# =========================================================
# AUTHENTICATION - REGISTER
# =========================================================

@app.post("/auth/register")
def register(
    user_data: RegisterRequest,
    db: Session = Depends(get_db),
):
    """
    Register a new user.
    """

    existing_user = (
        db.query(User)
        .filter(
            User.email == user_data.email
        )
        .first()
    )

    if existing_user:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    password_hash = hash_password(
        user_data.password
    )

    user = User(
        email=user_data.email,
        password_hash=password_hash,
        full_name=user_data.full_name,
    )

    db.add(user)
    db.commit()
    db.refresh(user)

    return {
        "message": "User registered successfully",
        "user_id": str(user.id),
    }


# =========================================================
# AUTHENTICATION - LOGIN
# =========================================================

@app.post(
    "/auth/login",
    response_model=TokenResponse,
)
def login(
    form_data: OAuth2PasswordRequestForm = Depends(),
    db: Session = Depends(get_db),
):
    """
    Login using email and password.

    Swagger OAuth2 uses:

        username = email
        password = password
    """

    user = (
        db.query(User)
        .filter(
            User.email == form_data.username
        )
        .first()
    )

    if not user:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    if not verify_password(
        form_data.password,
        user.password_hash,
    ):
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password",
        )

    access_token = create_access_token(
        data={
            "sub": str(user.id),
            "ver": user.token_version,
        }
    )

    refresh_token = create_refresh_token(
        data={
            "sub": str(user.id),
            "ver": user.token_version,
        }
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
    }

# =========================================================
# AUTHENTICATION - REFRESH TOKEN
# =========================================================

@app.post(
    "/auth/refresh",
    response_model=TokenResponse,
)
def refresh_access_token(
    request_data: RefreshRequest,
    db: Session = Depends(get_db),
):
    """
    Exchange a valid refresh token for a new access token
    (and a new refresh token, rotated for extra safety).
    """

    user_id, token_version = decode_refresh_token(
        request_data.refresh_token
    )

    user = (
        db.query(User)
        .filter(User.id == user_id)
        .first()
    )

    if not user:
        raise HTTPException(
            status_code=401,
            detail="User not found",
        )

    # A refresh token issued before the user signed out is
    # refused here too, otherwise signing out would only close
    # the door the access token walks through.
    if token_version != user.token_version:

        raise HTTPException(
            status_code=401,
            detail="Invalid or expired refresh token",
        )

    new_access_token = create_access_token(
        data={
            "sub": str(user.id),
            "ver": user.token_version,
        }
    )

    new_refresh_token = create_refresh_token(
        data={
            "sub": str(user.id),
            "ver": user.token_version,
        }
    )

    return {
        "access_token": new_access_token,
        "refresh_token": new_refresh_token,
        "token_type": "bearer",
    }

# =========================================================
# LOGOUT
# =========================================================

@app.post(
    "/auth/logout"
)
def logout(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Sign out everywhere.

    A JWT cannot be taken back once handed out: it is valid
    because it is correctly signed and not yet expired, and the
    server keeps no record of it to delete. Clearing it from the
    browser hides it, but a copy taken beforehand would keep
    working until it expired on its own.

    Raising token_version is what actually revokes it. Every
    token carries the version it was issued with, and
    get_current_user refuses any token whose version no longer
    matches the user's - so one write here kills every token
    this user holds, on every device, immediately.

    That breadth is the honest cost of the simplest design: it
    signs out the phone as well as the laptop. Per-device
    revocation would need a stored id per token.
    """

    current_user.token_version += 1

    db.commit()

    return {
        "message": "Signed out successfully"
    }


# =========================================================
# CURRENT USER - READ
# =========================================================

@app.get(
    "/auth/me",
    response_model=UserResponse,
)
def read_current_user(
    current_user: User = Depends(get_current_user),
):
    """
    The account behind the access token.

    This exists because the browser had no way to learn the
    student's name. It was written down at registration and
    kept in local storage, so the first sign-out lost it and
    the sidebar fell back to showing the email twice. A name
    the server can be asked for survives sign-out, a new
    browser and a second device.
    """

    return current_user


# =========================================================
# CURRENT USER - UPDATE NAME
# =========================================================

@app.patch(
    "/auth/me",
    response_model=UserResponse,
)
def update_current_user(
    profile_data: ProfileUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Rename the account holder.

    Returns the same shape as GET /auth/me, so the caller can
    put the response straight back into whatever it was
    displaying rather than re-fetching.
    """

    full_name = profile_data.full_name.strip()

    # A name of spaces is an empty name. Trimming first means
    # "   " is refused here rather than stored and then shown
    # as a blank line in the sidebar.
    if not full_name:

        raise HTTPException(
            status_code=400,
            detail="Name cannot be empty",
        )

    # 255 is the width of users.full_name. Refusing here gives
    # the student a sentence they can act on, instead of the
    # database raising a driver error further down.
    if len(full_name) > 255:

        raise HTTPException(
            status_code=400,
            detail="Name cannot be longer than 255 characters",
        )

    current_user.full_name = full_name

    db.commit()
    db.refresh(current_user)

    return current_user


# =========================================================
# CURRENT USER - CHANGE PASSWORD
# =========================================================

@app.post(
    "/auth/change-password",
    response_model=TokenResponse,
)
def change_password(
    password_data: ChangePasswordRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Replace the account password.

    Changing a password is also a way of saying "somebody else
    may be signed in as me", so it revokes every token this
    account holds - exactly as /auth/logout does, and through
    the same one line: token_version goes up, and every token
    minted before this moment stops being accepted.

    That would sign out the browser doing the changing too,
    which is why a fresh pair is minted and returned here. The
    student stays where they are; every other session ends.

    The length of new_password is checked by
    ChangePasswordRequest against MIN_PASSWORD_LENGTH, the same
    constant registration uses.
    """

    # verify_password, not a comparison of our own: this is the
    # same function /auth/login trusts, so a password that signs
    # in here is exactly a password that signs in there.
    if not verify_password(
        password_data.current_password,
        current_user.password_hash,
    ):

        raise HTTPException(
            status_code=400,
            detail="Current password is incorrect",
        )

    current_user.password_hash = hash_password(
        password_data.new_password
    )

    current_user.token_version += 1

    db.commit()
    db.refresh(current_user)

    # Minted after the commit, so they carry the raised version
    # and are the only tokens this account now has that
    # get_current_user will accept.
    access_token = create_access_token(
        data={
            "sub": str(current_user.id),
            "ver": current_user.token_version,
        }
    )

    refresh_token = create_refresh_token(
        data={
            "sub": str(current_user.id),
            "ver": current_user.token_version,
        }
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
    }


# =========================================================
# DOCUMENTS - UPLOAD
# =========================================================

@app.post(
    "/documents",
    response_model=DocumentResponse,
)
async def upload_document(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Upload a PDF document.

    The document is first saved to disk and the database.
    RAG processing is then started as a background task.

    The uploaded file is copied in blocks instead of being
    loaded completely into memory.
    """

    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="Filename is required",
        )

    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are supported",
        )

    os.makedirs(
        "uploads",
        exist_ok=True,
    )

    original_filename = file.filename

    safe_filename = (
        f"{uuid4()}_{original_filename}"
    )

    file_path = os.path.join(
        "uploads",
        safe_filename,
    )

    # -----------------------------------------------------
    # Save uploaded file in blocks
    # -----------------------------------------------------
    #
    # IMPORTANT:
    #
    # Do NOT use:
    #
    #     contents = await file.read()
    #
    # because that loads the entire PDF into memory.
    #
    # Instead, copy the file in chunks.
    # -----------------------------------------------------

    with open(
        file_path,
        "wb",
    ) as buffer:
        shutil.copyfileobj(
            file.file,
            buffer,
            length=1024 * 1024,
        )

    document = Document(
        user_id=current_user.id,
        title=original_filename,
        filename=original_filename,
        file_path=file_path,
        status="pending",
    )

    db.add(document)
    db.commit()
    db.refresh(document)

    background_tasks.add_task(
        process_document_background,
        document.id,
    )

    return document


# =========================================================
# GET ALL DOCUMENTS
# =========================================================

@app.get(
    "/documents",
    response_model=list[DocumentResponse],
)
def get_documents(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all documents belonging to the current user.
    """

    documents = (
        db.query(Document)
        .filter(
            Document.user_id == current_user.id
        )
        .all()
    )

    return documents


# =========================================================
# GET ONE DOCUMENT
# =========================================================

@app.get(
    "/documents/{document_id}",
    response_model=DocumentResponse,
)
def get_document(
    document_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a specific document.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    return document



# =========================================================
# UPDATE DOCUMENT TITLE
# =========================================================

@app.patch(
    "/documents/{document_id}",
    response_model=DocumentResponse,
)
def update_document(
    document_id: UUID,
    update_data: DocumentUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Update a document's display title.

    Only the title can be changed here. The underlying
    file, its path, and its processing status are never
    touched by this endpoint.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    new_title = update_data.title.strip()

    if not new_title:
        raise HTTPException(
            status_code=400,
            detail="Title cannot be empty",
        )

    document.title = new_title

    db.commit()
    db.refresh(document)

    return document

# =========================================================
# DELETE DOCUMENT
# =========================================================

@app.delete(
    "/documents/{document_id}"
)
def delete_document(
    document_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a document and its physical file.

    Related chunks, conversations and quizzes
    are deleted through database cascade relationships.
    """

    document = (
        db.query(Document)
        .filter(
            Document.id == document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    if (
        document.file_path
        and os.path.exists(document.file_path)
    ):
        os.remove(document.file_path)

    db.delete(document)
    db.commit()

    return {
        "message": "Document deleted successfully"
    }


# =========================================================
# CHAT
# =========================================================

@app.post(
    "/chat",
    response_model=ChatResponse,
)
def chat(
    chat_data: ChatRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Chat with a document using the RAG pipeline.

    The endpoint also loads the last few messages from
    the current conversation and passes them to the AI
    so that Claude can understand follow-up questions.
    """

    # -----------------------------------------------------
    # Validate message
    # -----------------------------------------------------

    if not chat_data.message.strip():
        raise HTTPException(
            status_code=400,
            detail="Message cannot be empty",
        )

    # -----------------------------------------------------
    # Validate document ownership
    # -----------------------------------------------------

    document = (
        db.query(Document)
        .filter(
            Document.id == chat_data.document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # -----------------------------------------------------
    # Document must be ready
    # -----------------------------------------------------

    if document.status != "ready":
        raise HTTPException(
            status_code=400,
            detail=(
                f"Document is not ready. "
                f"Current status: {document.status}"
            ),
        )

    # -----------------------------------------------------
    # Find existing conversation
    # -----------------------------------------------------

    conversation = None

    if chat_data.conversation_id:

        conversation = (
            db.query(Conversation)
            .filter(
                Conversation.id
                == chat_data.conversation_id,
                Conversation.user_id
                == current_user.id,
                Conversation.document_id
                == document.id,
            )
            .first()
        )

        if not conversation:
            raise HTTPException(
                status_code=404,
                detail="Conversation not found",
            )

    # -----------------------------------------------------
    # Create a new conversation if needed
    # -----------------------------------------------------

    if conversation is None:

        conversation = Conversation(
            user_id=current_user.id,
            document_id=document.id,
            title=chat_data.message[:255],
        )

        db.add(conversation)
        db.commit()
        db.refresh(conversation)

    # -----------------------------------------------------
    # LOAD PREVIOUS CONVERSATION MESSAGES
    # -----------------------------------------------------
    #
    # IMPORTANT:
    #
    # We load the previous messages BEFORE saving the
    # current user question.
    #
    # This means conversation_history contains only
    # messages that happened before the current question.
    #
    # Example:
    #
    # User: What is supply and demand?
    # Assistant: ...
    #
    # New question:
    # Explain that more simply.
    #
    # The history sent to Claude will contain the first
    # question and answer, while the new question is
    # sent separately.
    # -----------------------------------------------------

    previous_messages = (
        db.query(Message)
        .filter(
            Message.conversation_id
            == conversation.id
        )
        .order_by(
            Message.created_at.desc()
        )
        .limit(
            CHAT_HISTORY_LIMIT
        )
        .all()
    )

    # -----------------------------------------------------
    # Restore chronological order
    # -----------------------------------------------------
    #
    # The database query above returns the newest
    # messages first.
    #
    # Claude should receive them from oldest to newest.
    # -----------------------------------------------------

    previous_messages.reverse()

    # -----------------------------------------------------
    # Convert database messages into Claude format
    # -----------------------------------------------------

    conversation_history = [
        {
            "role": message.role,
            "content": message.content,
        }
        for message in previous_messages
    ]

    # -----------------------------------------------------
    # Save current user message
    # -----------------------------------------------------

    user_message = Message(
        conversation_id=conversation.id,
        role="user",
        content=chat_data.message,
        sources=[],
    )

    db.add(user_message)
    db.commit()

    # -----------------------------------------------------
    # Run RAG + conversation memory
    # -----------------------------------------------------

    try:

        rag_result = answer_question(
            db=db,
            document_id=document.id,
            question=chat_data.message,
            conversation_history=conversation_history,
        )

    except ValueError as error:

        raise HTTPException(
            status_code=400,
            detail=str(error),
        )

    except RuntimeError as error:

        raise HTTPException(
            status_code=503,
            detail=str(error),
        )

    except Exception as error:

        logger.exception(
            "Unhandled exception in /chat for document %s.",
            document.id,
        )

        raise HTTPException(
            status_code=500,
            detail=(
                "An error occurred while processing "
                f"the AI request: {error}"
            ),
        ) from error

    # -----------------------------------------------------
    # Save assistant response
    # -----------------------------------------------------

    assistant_message = Message(
        conversation_id=conversation.id,
        role="assistant",
        content=rag_result["answer"],
        sources=rag_result["sources"],
    )

    db.add(assistant_message)
    db.commit()

    # -----------------------------------------------------
    # Return response
    # -----------------------------------------------------

    return {
        "conversation_id": conversation.id,
        "answer": rag_result["answer"],
        "sources": rag_result["sources"],
    }


# =========================================================
# CONVERSATIONS
# =========================================================

@app.get("/conversations")
def get_conversations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get all conversations belonging to the current user,
    pinned first and newest first within each group.

    Pinning lifts a conversation to the top of the list it is
    already in rather than moving it to a favourites page: the
    web app groups these by document, and a favourites list would
    cut across that grouping - two organising schemes for the
    same rows, and two answers to "where is my conversation".
    The column can grow into a cross-document view later if that
    is ever wanted; a second list could not be simplified back
    down.

    The rows are Conversation objects, so is_pinned is part of
    each one alongside title and created_at.
    """

    conversations = (
        db.query(Conversation)
        .filter(
            Conversation.user_id == current_user.id
        )
        .order_by(
            Conversation.is_pinned.desc(),
            Conversation.created_at.desc(),
        )
        .all()
    )

    return conversations


# =========================================================
# GET ONE CONVERSATION
# =========================================================

@app.get(
    "/conversations/{conversation_id}"
)
def get_conversation(
    conversation_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a conversation and its messages.
    """

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == conversation_id,
            Conversation.user_id == current_user.id,
        )
        .first()
    )

    if not conversation:
        raise HTTPException(
            status_code=404,
            detail="Conversation not found",
        )

    messages = (
        db.query(Message)
        .filter(
            Message.conversation_id
            == conversation.id
        )
        .order_by(
            Message.created_at
        )
        .all()
    )

    return {
        "conversation": conversation,
        "messages": messages,
    }

# =========================================================
# UPDATE CONVERSATION - RENAME OR PIN
# =========================================================

@app.patch(
    "/conversations/{conversation_id}"
)
def update_conversation(
    conversation_id: UUID,
    update_data: ConversationUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Rename a conversation, pin it, or both.

    The same shape as update_quiz, deliberately: the web app
    drives both from the same kind of row control, and two
    endpoints that differ only in wording would be two things to
    remember.

    A conversation's title is set automatically from the first
    question asked, which is a reasonable guess and often not
    what the student would have called it - hence the rename.
    """

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == conversation_id,
            Conversation.user_id == current_user.id,
        )
        .first()
    )

    if not conversation:
        raise HTTPException(
            status_code=404,
            detail="Conversation not found",
        )

    # -----------------------------------------------------
    # What was actually sent
    # -----------------------------------------------------
    #
    # A PATCH with neither field cannot be what the caller meant,
    # so it is reported rather than absorbed silently as a no-op -
    # the same judgement update_quiz makes.

    if (
        update_data.title is None
        and update_data.is_pinned is None
    ):
        raise HTTPException(
            status_code=400,
            detail=(
                "Send a title, is_pinned, or both"
            ),
        )

    if update_data.title is not None:

        new_title = update_data.title.strip()

        if not new_title:
            raise HTTPException(
                status_code=400,
                detail="Title cannot be empty",
            )

        conversation.title = new_title

    if update_data.is_pinned is not None:
        conversation.is_pinned = update_data.is_pinned

    db.commit()
    db.refresh(conversation)

    return {
        "message": "Conversation updated successfully",
        "conversation": {
            "id": str(conversation.id),

            "title": conversation.title,

            "is_pinned": conversation.is_pinned,

            "document_id": (
                str(conversation.document_id)
                if conversation.document_id
                else None
            ),

            "created_at": (
                conversation.created_at.isoformat()
                if conversation.created_at
                else None
            ),
        },
    }


# =========================================================
# DELETE CONVERSATION
# =========================================================

@app.delete(
    "/conversations/{conversation_id}"
)
def delete_conversation(
    conversation_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a conversation and every message in it.

    Messages are removed through the database cascade,
    the same way delete_document removes a document's
    conversations.
    """

    conversation = (
        db.query(Conversation)
        .filter(
            Conversation.id == conversation_id,
            Conversation.user_id == current_user.id,
        )
        .first()
    )

    if not conversation:
        raise HTTPException(
            status_code=404,
            detail="Conversation not found",
        )

    db.delete(conversation)
    db.commit()

    return {
        "message": "Conversation deleted successfully"
    }


# =========================================================
# CREATE QUIZ
# =========================================================

@app.post("/quizzes")
def create_quiz(
    quiz_data: QuizCreateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Create an AI-generated quiz.

    The API endpoint is responsible for:

        1. Validating the document.
        2. Creating the Quiz record.
        3. Delegating AI quiz generation to ai.service.

    The actual AI generation logic is implemented
    in ai/service.py.
    """

    # -----------------------------------------------------
    # Validate document ownership
    # -----------------------------------------------------

    document = (
        db.query(Document)
        .filter(
            Document.id == quiz_data.document_id,
            Document.user_id == current_user.id,
        )
        .first()
    )

    if not document:

        raise HTTPException(
            status_code=404,
            detail="Document not found",
        )

    # -----------------------------------------------------
    # Document must be ready
    # -----------------------------------------------------

    if document.status != "ready":

        raise HTTPException(
            status_code=400,
            detail=(
                f"Document is not ready. "
                f"Current status: {document.status}"
            ),
        )

    # -----------------------------------------------------
    # Validate number of questions
    # -----------------------------------------------------

    if quiz_data.num_questions < 1:

        raise HTTPException(
            status_code=400,
            detail="num_questions must be at least 1",
        )

    if quiz_data.num_questions > 50:

        raise HTTPException(
            status_code=400,
            detail="num_questions cannot exceed 50",
        )

    # -----------------------------------------------------
    # Validate question types
    # -----------------------------------------------------
    #
    # An unknown type is rejected rather than ignored: silently
    # dropping it would hand back a quiz that does not match
    # what was asked for, with nothing to say why.

    if quiz_data.question_types is not None:

        unknown = [
            name
            for name in quiz_data.question_types
            if name not in QUESTION_TYPES
        ]

        if unknown:

            raise HTTPException(
                status_code=400,
                detail=(
                    f"Unknown question type(s): {', '.join(unknown)}. "
                    f"Allowed: {', '.join(QUESTION_TYPES)}"
                ),
            )

    # -----------------------------------------------------
    # Enough questions to go round
    # -----------------------------------------------------
    #
    # Every type the student picked gets at least one question,
    # so a quiz cannot have fewer questions than types picked.
    # Only types that were actually named count: omitting the
    # list is not a request for all three, it is the absence of
    # a preference, and the generator narrows its default to fit
    # the count rather than failing.
    #
    # Refused here rather than in the generator so the answer
    # comes back at once, instead of after a request to Claude
    # that was never going to work.

    requested_types = sorted(set(quiz_data.question_types or []))

    if quiz_data.num_questions < len(requested_types):

        raise HTTPException(
            status_code=400,
            detail=(
                f"{quiz_data.num_questions} question(s) is not "
                f"enough for {len(requested_types)} question "
                f"type(s): each type you pick needs at least "
                f"one question."
            ),
        )

    # -----------------------------------------------------
    # Validate the page range
    # -----------------------------------------------------
    #
    # Half a range is refused rather than completed: someone who
    # gave a first page and no last page may have meant "to the
    # end" or may simply not have finished typing, and quietly
    # choosing one of those builds a quiz from the wrong pages
    # with nothing to show that it happened.

    start_page = quiz_data.start_page
    end_page = quiz_data.end_page

    if (start_page is None) != (end_page is None):

        raise HTTPException(
            status_code=400,
            detail=(
                "Give both a first and a last page, or neither."
            ),
        )

    if start_page is not None:

        if start_page < 1:

            raise HTTPException(
                status_code=400,
                detail="The first page must be 1 or greater.",
            )

        if end_page < start_page:

            raise HTTPException(
                status_code=400,
                detail=(
                    "The last page cannot come before the first "
                    "page."
                ),
            )

        # A first page past the end of the document has nothing
        # behind it at all. The last page is left alone: pages
        # 90 to 200 of a 120 page document is a reasonable way
        # to say "to the end", and it still selects real pages.

        if (
            document.page_count
            and start_page > document.page_count
        ):

            raise HTTPException(
                status_code=400,
                detail=(
                    f"This document has {document.page_count} "
                    f"pages, so it has no page {start_page}."
                ),
            )

    # -----------------------------------------------------
    # Create Quiz record
    # -----------------------------------------------------

    quiz = Quiz(
        user_id=current_user.id,
        document_id=document.id,
        title=quiz_data.title,
    )

    db.add(quiz)
    db.flush()

    # -----------------------------------------------------
    # Generate questions through AI service
    # -----------------------------------------------------

    try:

        generated_questions, warnings = generate_quiz(
            db=db,
            quiz=quiz,
            question_count=quiz_data.num_questions,
            question_types=quiz_data.question_types,
            description=quiz_data.description,
            start_page=start_page,
            end_page=end_page,
        )

    except ValueError as error:

        db.rollback()

        raise HTTPException(
            status_code=400,
            detail=str(error),
        )

    except RuntimeError as error:

        db.rollback()

        raise HTTPException(
            status_code=503,
            detail=str(error),
        )

    except Exception as error:

        db.rollback()

        raise HTTPException(
            status_code=500,
            detail=(
                "An error occurred while generating "
                "the quiz."
            ),
        ) from error

    # -----------------------------------------------------
    # Return result
    # -----------------------------------------------------

    # warnings is empty for a quiz that is exactly what was
    # asked for. When it is not, it says what the quiz did not
    # manage to be - a question type that produced nothing, say
    # - in words meant for the student rather than a log file.

    return {
        "message": "Quiz created successfully",
        "quiz_id": str(quiz.id),
        "questions_count": len(
            generated_questions
        ),
        "warnings": warnings,
    }

# =========================================================
# LIST QUIZZES
# =========================================================

@app.get(
    "/quizzes"
)
def list_quizzes(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Every quiz this user has created, newest first.

    Without this the web app had no way to ask which
    quizzes exist, so it kept a list in the browser's
    local storage: lost on another device, on another
    browser, and whenever site data was cleared - while
    the quizzes themselves sat in the database,
    unreachable because nothing listed them.

    Counts are gathered in two extra queries rather than
    one per quiz.
    """

    # Pinned first, then newest first inside each group.
    #
    # Pinning lifts a quiz to the top of the list it is already
    # in rather than moving it to a favourites page: this list is
    # grouped by document, and a favourites list would cut across
    # that grouping - two organising schemes for the same rows,
    # and two answers to "where is my quiz". The column could
    # grow into a cross-document view later if that is ever
    # wanted; a second list could not be simplified back down.

    quizzes = (
        db.query(Quiz)
        .filter(
            Quiz.user_id == current_user.id
        )
        .order_by(
            Quiz.is_pinned.desc(),
            Quiz.created_at.desc(),
        )
        .all()
    )

    if not quizzes:
        return {"quizzes": []}

    quiz_ids = [quiz.id for quiz in quizzes]

    # -----------------------------------------------------
    # How many questions, how many attempts
    # -----------------------------------------------------

    question_counts = {}

    for (quiz_id,) in (
        db.query(QuizQuestion.quiz_id)
        .filter(
            QuizQuestion.quiz_id.in_(quiz_ids)
        )
        .all()
    ):
        question_counts[quiz_id] = (
            question_counts.get(quiz_id, 0) + 1
        )

    attempt_counts = {}

    for (quiz_id,) in (
        db.query(QuizAttempt.quiz_id)
        .filter(
            QuizAttempt.quiz_id.in_(quiz_ids)
        )
        .all()
    ):
        attempt_counts[quiz_id] = (
            attempt_counts.get(quiz_id, 0) + 1
        )

    # -----------------------------------------------------
    # Which document each quiz came from
    # -----------------------------------------------------
    #
    # A quiz can outlive its document, so a missing title
    # is normal and is returned as null rather than
    # dropping the quiz from the list.

    document_ids = [
        quiz.document_id
        for quiz in quizzes
        if quiz.document_id is not None
    ]

    document_titles = {}

    if document_ids:

        for document_id, title in (
            db.query(
                Document.id,
                Document.title,
            )
            .filter(
                Document.id.in_(document_ids)
            )
            .all()
        ):
            document_titles[document_id] = title

    # -----------------------------------------------------
    # Return
    # -----------------------------------------------------

    return {
        "quizzes": [
            {
                "id": str(quiz.id),

                "title": quiz.title,

                "is_pinned": quiz.is_pinned,

                "document_id": (
                    str(quiz.document_id)
                    if quiz.document_id
                    else None
                ),

                "document_title": document_titles.get(
                    quiz.document_id
                ),

                "questions_count": question_counts.get(
                    quiz.id, 0
                ),

                "attempts_count": attempt_counts.get(
                    quiz.id, 0
                ),

                "created_at": (
                    quiz.created_at.isoformat()
                    if quiz.created_at
                    else None
                ),
            }
            for quiz in quizzes
        ]
    }

# =========================================================
# GET QUIZ
# =========================================================

@app.get("/quizzes/{quiz_id}")
def get_quiz(
    quiz_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Get a quiz and its questions.

    IMPORTANT:

    correct_answer and explanation are NOT returned
    because they must remain hidden from the student
    until the quiz is submitted.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .order_by(
            QuizQuestion.question_index
        )
        .all()
    )

    return {
        "quiz": {
            "id": quiz.id,
            "title": quiz.title,
            "document_id": quiz.document_id,
            "created_at": quiz.created_at,
        },

        "questions": [
            QuizQuestionResponse.model_validate(
                question
            )
            for question in questions
        ],
    }


# =========================================================
# SUBMIT QUIZ ATTEMPT
# =========================================================

@app.post(
    "/quizzes/{quiz_id}/attempts"
)
def submit_quiz_attempt(
    quiz_id: UUID,
    attempt_data: QuizAttemptRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Submit answers and calculate the final score.

    Multiple choice and true/false are compared as
    strings, which is what they are: one letter, or
    "true" / "false".

    Short answers are not. The stored correct answers
    average 16.9 words and only 2 of 24 are three words
    or shorter, so string comparison marked a student
    who was right in their own words as wrong. Those are
    graded by meaning instead, and can come back
    "partial": one true part of a multi-part answer.
    A partial answer earns the mark and the student is
    told what was missing.

    Grading is one small model call per short answer, so
    the answers are graded concurrently rather than one
    after another.
    """

    # -----------------------------------------------------
    # How long it took
    # -----------------------------------------------------
    #
    # Checked before anything else is done, so a nonsense
    # duration costs nothing: rejecting it after grading would
    # mean paying for the model calls and then throwing the
    # attempt away.
    #
    # The number is measured in the browser and cannot be
    # trusted, only bounded. A negative duration or one longer
    # than a day did not happen, so it is refused rather than
    # written into the table as a fact.

    duration_seconds = attempt_data.duration_seconds

    if duration_seconds is not None:

        if (
            duration_seconds < 0
            or duration_seconds > MAX_ATTEMPT_DURATION_SECONDS
        ):

            raise HTTPException(
                status_code=400,
                detail=(
                    "duration_seconds must be between 0 and "
                    f"{MAX_ATTEMPT_DURATION_SECONDS}"
                ),
            )

    # -----------------------------------------------------
    # Find quiz
    # -----------------------------------------------------

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    # -----------------------------------------------------
    # Get questions
    # -----------------------------------------------------

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .all()
    )

    if not questions:

        raise HTTPException(
            status_code=400,
            detail="This quiz has no questions.",
        )

    # -----------------------------------------------------
    # Validate answers
    # -----------------------------------------------------

    submitted_answers = (
        attempt_data.answers
    )

    total_questions = len(questions)

    results = []

    # -----------------------------------------------------
    # Grade the short answers, concurrently
    # -----------------------------------------------------
    #
    # Everything the grader needs is pulled out of the ORM
    # objects first, so nothing touches the database from
    # inside a worker thread.

    to_grade = []

    for question in questions:

        if question.question_type != "short_answer":
            continue

        student_answer = submitted_answers.get(
            str(question.id)
        )

        if student_answer is None:
            continue

        if not str(student_answer).strip():
            continue

        to_grade.append(
            (
                str(question.id),
                str(question.question_text),
                str(question.correct_answer),
                str(student_answer),
            )
        )

    grade_by_question_id = {}

    if to_grade:

        with ThreadPoolExecutor(
            max_workers=min(len(to_grade), 8)
        ) as pool:

            futures = {
                pool.submit(
                    grade_short_answer,
                    question_text,
                    correct_answer,
                    student_answer,
                ): question_id
                for (
                    question_id,
                    question_text,
                    correct_answer,
                    student_answer,
                ) in to_grade
            }

            for future in futures:

                question_id = futures[future]

                # grade_short_answer never raises - it falls
                # back to exact comparison on its own - so a
                # failure here would be a bug, not an outage.
                grade_by_question_id[question_id] = (
                    future.result()
                )

    # -----------------------------------------------------
    # Compare answers
    # -----------------------------------------------------

    correct_count = 0
    partial_count = 0

    for question in questions:

        question_id = str(
            question.id
        )

        student_answer = submitted_answers.get(
            question_id
        )

        grade = grade_by_question_id.get(
            question_id
        )

        if grade is not None:

            # A short answer that was graded. The student's
            # own text is kept exactly as they wrote it, so
            # the review screen shows their sentence rather
            # than an upper-cased version of it.
            student_answer = str(
                student_answer
            ).strip()

            verdict = grade["verdict"]
            reason = grade["reason"]

        else:

            if student_answer is not None:

                student_answer = str(
                    student_answer
                ).strip().upper()

            expected_answer = (
                str(
                    question.correct_answer
                )
                .strip()
                .upper()
            )

            verdict = (
                "correct"
                if student_answer == expected_answer
                else "incorrect"
            )

            reason = ""

        if verdict == "correct":
            correct_count += 1

        elif verdict == "partial":
            partial_count += 1

        results.append(
            {
                "question_id": question_id,
                "student_answer": student_answer,

                # Kept so that anything reading only
                # `correct` still works. A partial answer
                # earned the mark, so it is true here.
                "correct": verdict in {"correct", "partial"},

                "verdict": verdict,
                "reason": reason,

                # Sent here and nowhere else. GET
                # /quizzes/{id} deliberately omits these,
                # so before the student answers there is
                # nothing to read - not in the page, and
                # not in the network response behind it.
                "correct_answer": str(
                    question.correct_answer
                ),

                "explanation": question.explanation or "",
            }
        )

    # -----------------------------------------------------
    # Calculate percentage
    # -----------------------------------------------------

    score = correct_count + partial_count

    percentage = round(
        (score / total_questions) * 100,
        2,
    )

    # -----------------------------------------------------
    # Save attempt
    # -----------------------------------------------------

    attempt = QuizAttempt(
        quiz_id=quiz.id,
        user_id=current_user.id,
        score=score,
        answers=submitted_answers,
        duration_seconds=duration_seconds,
    )

    db.add(attempt)
    db.commit()
    db.refresh(attempt)

    # -----------------------------------------------------
    # Return final result
    # -----------------------------------------------------

    return {
        "message": "Quiz attempt submitted successfully",

        "attempt_id": str(
            attempt.id
        ),

        "score": score,

        "total_questions": total_questions,

        "percentage": percentage,

        "correct_answers": correct_count,

        "partial_answers": partial_count,

        "wrong_answers": (
            total_questions
            - correct_count
            - partial_count
        ),

        "results": results,
    }

# =========================================================
# LIST QUIZ ATTEMPTS
# =========================================================

@app.get(
    "/quizzes/{quiz_id}/attempts"
)
def list_quiz_attempts(
    quiz_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Every attempt this user has made at this quiz,
    newest first.

    Only the score is available. The per-question
    verdicts are worked out at submission time and sent
    to the browser, but never stored, so a past attempt
    can show what was scored and not which questions
    were missed.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    # -----------------------------------------------------
    # How many questions the quiz has
    # -----------------------------------------------------
    #
    # Questions are written once when the quiz is created
    # and never change, so today's count is also the count
    # every past attempt was scored against.

    total_questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .count()
    )

    attempts = (
        db.query(QuizAttempt)
        .filter(
            QuizAttempt.quiz_id == quiz.id,
            QuizAttempt.user_id == current_user.id,
        )
        .order_by(
            QuizAttempt.completed_at.desc()
        )
        .all()
    )

    return {
        "total_questions": total_questions,

        "attempts": [
            {
                "id": str(attempt.id),

                "score": attempt.score,

                "total_questions": total_questions,

                "percentage": (
                    round(
                        (attempt.score / total_questions) * 100,
                        2,
                    )
                    if total_questions
                    else None
                ),

                "completed_at": (
                    attempt.completed_at.isoformat()
                    if attempt.completed_at
                    else None
                ),

                # None for every attempt recorded before the
                # timer existed. The browser shows a dash for
                # those rather than a misleading 00:00.
                "duration_seconds": attempt.duration_seconds,
            }
            for attempt in attempts
        ],
    }
# =========================================================
# GET ONE QUIZ ATTEMPT
# =========================================================

@app.get(
    "/quizzes/{quiz_id}/attempts/{attempt_id}"
)
def get_quiz_attempt(
    quiz_id: UUID,
    attempt_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    One past attempt, question by question: what was asked,
    what the student wrote, and what the correct answer was.

    The verdicts are not stored, so they are worked out again
    here - but only where that costs nothing and cannot
    disagree with the original marking. Multiple choice and
    true/false are string comparisons, exactly as they were at
    submission time, so re-running them is deterministic.

    Short answers were marked by the model on meaning. Marking
    them again would be a paid call per question and could
    return a different verdict from the one the student saw,
    so `verdict` is null for them and both answers are shown
    side by side instead.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:

        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    attempt = (
        db.query(QuizAttempt)
        .filter(
            QuizAttempt.id == attempt_id,
            QuizAttempt.quiz_id == quiz.id,
            QuizAttempt.user_id == current_user.id,
        )
        .first()
    )

    if not attempt:

        raise HTTPException(
            status_code=404,
            detail="Attempt not found",
        )

    questions = (
        db.query(QuizQuestion)
        .filter(
            QuizQuestion.quiz_id == quiz.id
        )
        .order_by(
            QuizQuestion.question_index
        )
        .all()
    )

    submitted_answers = attempt.answers or {}

    total_questions = len(questions)

    rows = []

    for question in questions:

        student_answer = submitted_answers.get(
            str(question.id)
        )

        # -------------------------------------------------
        # Re-mark only what can be re-marked for free
        # -------------------------------------------------

        verdict = None

        if question.question_type in {
            "multiple_choice",
            "true_false",
        }:

            if (
                student_answer is None
                or not str(student_answer).strip()
            ):

                verdict = "incorrect"

            else:

                verdict = (
                    "correct"
                    if str(student_answer).strip().upper()
                    == str(question.correct_answer).strip().upper()
                    else "incorrect"
                )

        rows.append(
            {
                "id": str(question.id),

                "question_index": question.question_index,

                "question_text": question.question_text,

                "question_type": question.question_type,

                "options": question.options,

                "student_answer": student_answer,

                "correct_answer": str(
                    question.correct_answer
                ),

                "explanation": question.explanation or "",

                "source_page": question.source_page,

                "verdict": verdict,
            }
        )

    return {
        "attempt": {
            "id": str(attempt.id),

            "score": attempt.score,

            "total_questions": total_questions,

            "percentage": (
                round(
                    (attempt.score / total_questions) * 100,
                    2,
                )
                if total_questions
                else None
            ),

            "completed_at": (
                attempt.completed_at.isoformat()
                if attempt.completed_at
                else None
            ),

            # Same as the list endpoint, so a caller reading one
            # attempt sees the field it already knows from the
            # table it clicked through from.
            "duration_seconds": attempt.duration_seconds,
        },

        "questions": rows,
    }

# =========================================================
# UPDATE QUIZ - RENAME OR PIN
# =========================================================

@app.patch(
    "/quizzes/{quiz_id}"
)
def update_quiz(
    quiz_id: UUID,
    update_data: QuizUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Rename a quiz, pin it, or both.

    PATCH rather than PUT: only the fields being changed are
    sent. The questions, the document they came from and every
    recorded attempt are neither sent nor replaced, so this is
    not a full representation of the quiz and PUT would claim it
    was.

    The two fields arrive independently - the pin control has no
    reason to know the title, and the rename form has no reason
    to know the pin - so either may be omitted.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:
        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    # -----------------------------------------------------
    # What was actually sent
    # -----------------------------------------------------
    #
    # A PATCH with neither field is refused rather than quietly
    # succeeding. It cannot be what the caller meant, and a 200
    # for it would hide the bug that produced it.

    if (
        update_data.title is None
        and update_data.is_pinned is None
    ):
        raise HTTPException(
            status_code=400,
            detail=(
                "Send a title, is_pinned, or both"
            ),
        )

    if update_data.title is not None:

        new_title = update_data.title.strip()

        if not new_title:
            raise HTTPException(
                status_code=400,
                detail="Title cannot be empty",
            )

        quiz.title = new_title

    if update_data.is_pinned is not None:
        quiz.is_pinned = update_data.is_pinned

    db.commit()
    db.refresh(quiz)

    return {
        "message": "Quiz updated successfully",
        "quiz": {
            "id": str(quiz.id),
            "title": quiz.title,
            "is_pinned": quiz.is_pinned,
        },
    }


# =========================================================
# DELETE QUIZ
# =========================================================

@app.delete(
    "/quizzes/{quiz_id}"
)
def delete_quiz(
    quiz_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a quiz, its questions, and every attempt
    recorded against it.

    The attempts go too, and they are the only record of
    what the student scored - so this is not undoable and
    the interface asks before calling it.
    """

    quiz = (
        db.query(Quiz)
        .filter(
            Quiz.id == quiz_id,
            Quiz.user_id == current_user.id,
        )
        .first()
    )

    if not quiz:
        raise HTTPException(
            status_code=404,
            detail="Quiz not found",
        )

    db.delete(quiz)
    db.commit()

    return {
        "message": "Quiz deleted successfully"
    }